-- Per-user SOS viewed/pinned state.
-- Run in Supabase SQL Editor or any PostgreSQL client connected to the target DB.

CREATE TABLE IF NOT EXISTS "PingUserStates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PingId" integer NOT NULL,
    "UserId" text NOT NULL,
    "ViewedAt" timestamp with time zone NULL,
    "IsPinned" boolean NOT NULL DEFAULT false,
    "PinnedAt" timestamp with time zone NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "FK_PingUserStates_Pings_PingId"
        FOREIGN KEY ("PingId") REFERENCES "Pings" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PingUserStates_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_PingUserStates_UserId_PingId"
    ON "PingUserStates" ("UserId", "PingId");

CREATE INDEX IF NOT EXISTS "IX_PingUserStates_UserId_IsPinned"
    ON "PingUserStates" ("UserId", "IsPinned");

CREATE INDEX IF NOT EXISTS "IX_PingUserStates_PingId"
    ON "PingUserStates" ("PingId");
