-- 2026-04-23: create DonationRecords for PayOS donate history.
-- This script intentionally provisions only the donate table.
-- Do not stamp __EFMigrationsHistory with AddDonationRecords yet because the current EF migration file
-- also bundles unrelated DirectConversation/DirectMessage and user-profile columns.

BEGIN;

CREATE TABLE IF NOT EXISTS "DonationRecords"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderCode" bigint NOT NULL,
    "PaymentLinkId" character varying(100),
    "UserId" text,
    "DisplayName" character varying(200) NOT NULL,
    "MaskedPhone" character varying(20),
    "Amount" bigint NOT NULL,
    "Message" character varying(200),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PaidAt" timestamp with time zone NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_DonationRecords_OrderCode"
    ON "DonationRecords" ("OrderCode");

CREATE INDEX IF NOT EXISTS "IX_DonationRecords_Status"
    ON "DonationRecords" ("Status");

CREATE INDEX IF NOT EXISTS "IX_DonationRecords_PaidAt"
    ON "DonationRecords" ("PaidAt");

CREATE INDEX IF NOT EXISTS "IX_DonationRecords_UserId"
    ON "DonationRecords" ("UserId");

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_DonationRecords_AspNetUsers_UserId'
    ) THEN
        ALTER TABLE "DonationRecords"
        ADD CONSTRAINT "FK_DonationRecords_AspNetUsers_UserId"
        FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id")
        ON DELETE SET NULL;
    END IF;
END $$;

COMMIT;