namespace ReliefConnect.Core.Entities;

/// <summary>
/// Individual message in a chatbot conversation (REQ-BOT-01).
/// </summary>
public class Message
{
    public int Id { get; set; }

    public string Content { get; set; } = string.Empty;

    /// <summary>True if this message was generated by the AI bot</summary>
    public bool IsBotMessage { get; set; } = false;

    /// <summary>True if safety fallback was triggered (REQ-BOT-03)</summary>
    public bool HasSafetyWarning { get; set; } = false;

    public DateTime SentAt { get; set; } = DateTime.UtcNow;

    // Foreign keys
    public int ConversationId { get; set; }
    public Conversation Conversation { get; set; } = null!;

    public string? SenderId { get; set; }
    public ApplicationUser? Sender { get; set; }
}
